import { Head } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import PageHeader from '../../Components/PageHeader';
import Rule from '../../Components/Rule';

/**
 * Terms of service.
 *
 * Deliberately short and specific to what this app actually is: a free,
 * no-payment, personal project with a recommendation feature that is a
 * suggestion rather than an authority.
 */
export default function Terms({ updated, contactEmail }) {
    return (
        <AppLayout>
            <Head title="Terms of Service" />

            <div className="mx-auto max-w-2xl px-6 py-16">
                <PageHeader
                    eyebrow="Legal"
                    accent="Service"
                    subline={`Last updated ${updated}.`}
                >
                    Terms of
                </PageHeader>

                <div className="space-y-12 text-[15px] leading-relaxed text-[var(--muted)]">
                    <section>
                        <Rule label="What this is" />
                        <p>
                            Parfum de Climat is a free personal project that suggests fragrances
                            from your collection based on your local weather. There is no charge,
                            no subscription, and nothing to buy.
                        </p>
                    </section>

                    <section>
                        <Rule label="The recommendations" />
                        <p>
                            Recommendations are generated by scoring the notes in a fragrance
                            against the current temperature, humidity and season. They are a
                            suggestion, not expert advice. Fragrance is subjective, the underlying
                            note data comes from a community-compiled catalogue and may be
                            incomplete or wrong, and the weather comes from a third-party service
                            that can be inaccurate or unavailable.
                        </p>
                    </section>

                    <section>
                        <Rule label="Your account" />
                        <ul className="space-y-2 list-disc pl-5">
                            <li>Keep your password to yourself. You are responsible for what happens under your account.</li>
                            <li>Use a real email address you control, so account recovery can reach you.</li>
                            <li>One person, one account. Do not create accounts automatically.</li>
                            <li>You can close your account at any time by emailing the address below.</li>
                        </ul>
                    </section>

                    <section>
                        <Rule label="Fair use" />
                        <p>
                            Please do not scrape the catalogue, hammer the API, attempt to break
                            authentication, or use the service to store anything unlawful. Requests
                            are rate limited, and accounts that abuse the service may be suspended
                            without notice.
                        </p>
                    </section>

                    <section>
                        <Rule label="The catalogue" />
                        <p>
                            Fragrance names, brands, notes and images come from publicly available
                            community sources and remain the property of their respective owners.
                            They are shown here for reference. If you own material shown here and
                            want it removed, email the address below and it will be taken down.
                        </p>
                    </section>

                    <section>
                        <Rule label="Availability" />
                        <p>
                            This is a personal project running on free infrastructure. It may be
                            slow, go offline, lose data, or stop existing, with no notice and no
                            guarantee of any kind. Do not rely on it as the only record of
                            anything you care about.
                        </p>
                    </section>

                    <section>
                        <Rule label="Changes" />
                        <p>
                            These terms may change as the app changes. The date at the top reflects
                            the last revision. Continuing to use the service after a change means
                            you accept it.
                        </p>
                    </section>

                    <section>
                        <Rule label="Contact" />
                        <p>
                            <a href={`mailto:${contactEmail}`} className="text-[var(--color-accent)] hover:underline">
                                {contactEmail}
                            </a>
                        </p>
                    </section>
                </div>
            </div>
        </AppLayout>
    );
}
